<?php

/**
 * @asanchez75
 * [stats_custom_theme description]
 * @return [type] [description]
 */
function stats_custom_theme() {
  global $conf;
  $args = arg();

  // Set the admin theme when viewing a diff comparison with the diff module.
  if (isset($args[0]) && $args[0] == "stats") {
    return array($conf['admin_theme']);
  }
}

/**
 * [stats_init description]
 * @return [type] [description]
 */
function stats_init() {
  drupal_add_library('system', 'ui.datepicker');
  drupal_add_js("(function ($) { $('.datepicker').datepicker(); })(jQuery);", array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
}

/**
 * [stats_menu description]
 * @return [type] [description]
 */
function stats_menu() {
  $items['stats/nodes'] = array(
    'title' => 'total number of nodes per content type',
    'description' => 'total number of nodes per content type',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stats_page_form'),
  );
  return $items;
}

/**
 * [stats_page_form description]
 * @return [type] [description]
 */
function stats_page_form() {

  $form['display'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="display">',
    '#suffix' => '</div>',
  );

  $form['start_date'] = array(
    '#type' => 'textfield',
    '#attributes' => array('class' => array('datepicker')),
  );

  $form['end_date'] = array(
    '#type' => 'textfield',
    '#attributes' => array('class' => array('datepicker')),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
    '#ajax' => array(
      'callback' => 'stats_page_form_submit',
      'wrapper' => 'display',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  return $form;
}

/**
 * [stats_page_form_submit description]
 * @param  [type] $form        [description]
 * @param  [type] &$form_state [description]
 * @return [type]              [description]
 */
function stats_page_form_submit($form, &$form_state) {

  $form_state['rebuild'] = true;

  $start_date = strtotime($form_state['values']['start_date']);
  $end_date = strtotime($form_state['values']['end_date']);

  $query = db_select('node', 'n');
  $query->fields('n', array('type'));
  $query->condition('n.status', 1);
  $query->condition('n.created', array($start_date, $end_date), 'BETWEEN');
  $query->groupBy('n.type');
  $query->addExpression('COUNT(*)', 'counter');
  $rows = $query->execute()->fetchAll();
  $header = array('type', 'total');
  foreach ($rows as $row) {
    $data[] = array($row->type, $row->counter);
  }

  if (!empty($data)) {
    return '<div id="display">' . theme('table', array('header' => $header, 'rows' => $data)) . '</div>';
  }
  else {
    return array();
  }

}
